apiVersion: v1
kind: Service
metadata:
  name: k8s-insight-controller
  namespace: k8s-insight-system
spec:
  selector:
    app.kubernetes.io/name: k8s-insight-controller
  ports:
    - name: web
      port: 8090
      targetPort: web
    - name: metrics
      port: 8080
      targetPort: metrics
